<?xml version="1.0" encoding="utf-8"?><Database Name="student" Class="studentDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\student.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="studentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.student1" Member="student1s">
    <Type Name="student1">
      <Column Name="sid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sem" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="cpi" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="contactno" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="emailid" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>